import { ToolEvents, GlobalEvents } from "../agent-types";
// IMPORTANT: Tool event continuation messages are generated by prepareMessages() BEFORE
// processConfirmations() runs. This affects what "confirmed"/"declined" messages can safely say:
//
// - confirm_before_execution tools (call_system, create_system, edit_system):
//   Neither the tool nor processConfirmation has run yet. NEVER assert outcomes.
//
// - confirm_after_execution tools (edit_tool, edit_payload, authenticate_oauth):
//   The tool already executed, but processConfirmation hasn't. Can reference the tool result,
//   but only assert post-confirmation outcomes if processConfirmation is deterministic (e.g. applying a diff).
//
// - Other events (oauth_success, oauth_failure, manual_run_success, manual_run_failure):
//   Fired by the UI after the outcome is known. CAN describe outcomes.
export const TOOL_EVENTS: ToolEvents = {
  call_system: {
    confirmed: {
      message: "[USER ACTION] The user clicked the confirm button to execute the system call.",
      statusUpdate: "running",
    },
    declined: {
      message: "[USER ACTION] The user clicked the decline button to cancel the system call.",
      statusUpdate: "declined",
    },
  },
  edit_tool: {
    confirmed: {
      message:
        "[USER ACTION] The user approved the tool edit changes. The changes have been applied to the tool configuration.",
      statusUpdate: "completed",
    },
    declined: {
      message: "[USER ACTION] The user rejected the tool edit changes.",
      statusUpdate: "declined",
    },
    partial: {
      message:
        "[USER ACTION] The user PARTIALLY approved the tool edit. IMPORTANT: Check the tool output for 'appliedChanges' and 'rejectedChanges'.",
      statusUpdate: "completed",
    },
    request_fix: {
      message:
        '[USER ACTION] User clicked "Request Fix". Error: {error}. Please fix using edit_tool.',
    },
    manual_run_success: {
      message:
        '[USER ACTION] User clicked the "Test with N changes" button. Execution succeeded. Result preview: {result}',
    },
    manual_run_failure: {
      message:
        '[USER ACTION] User clicked the "Test with N changes" button but it FAILED with error: {error}.',
    },
  },
  edit_payload: {
    confirmed: {
      message:
        "[USER ACTION] The user approved the payload edit. The payload has been updated in the playground.",
      statusUpdate: "completed",
    },
    declined: {
      message: "[USER ACTION] The user rejected the payload edit.",
      statusUpdate: "declined",
    },
  },
  create_system: {
    confirmed: {
      message: "[USER ACTION] The user provided credentials and clicked the confirm button.",
      statusUpdate: "running",
    },
    declined: {
      message: "[USER ACTION] The user declined system creation.",
      statusUpdate: "declined",
    },
  },
  edit_system: {
    confirmed: {
      message: "[USER ACTION] The user provided credentials and confirmed the system edit.",
      statusUpdate: "running",
    },
    declined: {
      message: "[USER ACTION] The user declined the system edit.",
      statusUpdate: "declined",
    },
  },
  authenticate_oauth: {
    oauth_success: {
      message:
        '[SYSTEM] OAuth authentication for "{systemId}" completed successfully. Access token saved.',
      statusUpdate: "completed",
    },
    oauth_failure: {
      message: '[SYSTEM] OAuth authentication for "{systemId}" failed: {error}.',
      statusUpdate: "failed",
    },
  },
  run_tool: {
    manual_run_success: {
      message: "[USER ACTION] User tested the tool. Execution succeeded. Result preview: {result}",
    },
    manual_run_failure: {
      message: "[USER ACTION] User tested the tool but it FAILED with error: {error}.",
    },
  },
  build_tool: {
    manual_run_success: {
      message:
        '[USER ACTION] User clicked the "Run Tool" button. Execution succeeded. Result preview: {result}',
    },
    manual_run_failure: {
      message:
        '[USER ACTION] User clicked the "Run Tool" button but it FAILED with error: {error}.',
    },
    manual_save_success: {
      message:
        '[USER ACTION] User saved the tool via the Save button. Tool ID: "{toolId}". The tool is now persisted — do NOT call save_tool.',
    },
  },
};

export const GLOBAL_EVENTS: GlobalEvents = {
  file_upload: {
    message:
      "[SYSTEM] User uploaded files. Available files:\n{fileList}\n\nFile content previews:\n{previews}",
  },
};

export function resolveEventMessage(template: string, payload?: Record<string, unknown>): string {
  if (!payload) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => {
    const value = payload[key];
    if (value === undefined) return `{${key}}`;
    if (typeof value === "object") {
      const str = JSON.stringify(value);
      return str.length > 500 ? str.substring(0, 500) + "..." : str;
    }
    return String(value);
  });
}
